### ISSUE TITLE
fula.connect always returns true

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/react-native-fula#1]
`connect `method always returns true even if the endpoints (boxAddr) are wrong:

For example at a local environment all these addresses returns true:
Correct address;  '/ip4/`192.168.0.200`/tcp/4002/p2p/PeerId.....'
Wrong: address:  '/ip4/`192.168.0.201`/tcp/4002/p2p/PerrtId....'

**Comment by farhoud** [comment]
@ghorbani-m 
For decreasing the battery usage i don't dial and connect the peer i just add the peer to PeerStore for later request's.
When user ask for  send/receive operation connecting and opening the stream happens.

## Proposal 
Change `Connect` to `addBox`
