### ISSUE TITLE
Ping the box

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/react-native-fula#13]
Sometimes we just need to check the box connectivity or test the box connection, for now we have to send a file to detect weather the box is available or not.

**Comment by farhoud** [comment]
Do you need a health-check or just a ping?
We may have multiple boxes that connected at once.
How should API look like?

**Comment by ghorbani-m** [comment]
I don't know what is difference between health-check and ping,so let me define some use cases:
- Before sending/receiving a file I need to check the box availability for better UI action (or for faster response if is possible)
- When the user wants to add a Box's address we can allow the user to test the address to makes sure the address is correct or accessible

**Comment by ehsan6sha** [comment]
in the revised version there is a connectionCheck mthod for it
