### ISSUE TITLE
receiveMeta in file protocol

### ISSUE THREAD

**Issue by mehdibalouchi** [functionland/react-native-fula#16]
A method for receiving a file's metadata from a box by providing its CID

**Comment by ghorbani-m** [comment]
@mehdibalouchi Can you elaborate, on what kind of information we get/put with `receiveMeta`?

**Comment by mehdibalouchi** [comment]
`meta` is one of the actions defined in the file protocol ([see here](https://github.com/functionland/fula/blob/main/protocols/file/src/schema/index.proto)). When you upload a file with the file protocol using the `send` action, its metadata gets stored with it. You can then retrieve a file's metadata with the file protocol using the `meta` action.
current structure of the metadata is:
```protobuf
message Meta {
  string name = 1;
  string type = 2;
  uint64 size = 3 [jstype = JS_NUMBER];
  int64 lastModified = 4 [jstype = JS_NUMBER];
  optional bytes preview = 5;
}
```
`meta` is currently implemented in [fula-client](https://github.com/functionland/fula/blob/01b99fef03945beec4a9e41c0d6cb13291fd6cae/libraries/fula-client/src/index.ts#L201) and in [go-fula](https://github.com/functionland/go-fula/blob/4c9150b2848bbc2a049e0d323ff04a0c7b805a98/protocols/file/file.go#L43) libraries, but not in the `react-native-fula`

**Comment by ehsan6sha** [comment]
changed the protocol to wnfs
